api:
  weather_key: "cc8a12efcb214d79b6478d309889b6bb"
  news_key: "1b3cad58dd274546ad0008e7228d8ab4"
  gnews_key: "76f2537e330e6fa8aa565f0cc97d60af"  # 替换为你的 GNews API 密钥
responses:
  recognition_error: "语音识别失败，请重试"
  network_error: "网络错误"
  weather_not_found: "无法找到 {city} 的天气信息"
  unknown_command: "无法识别该指令"
  no_sound: "没听到声音，请再说一次"
  turn_on_light: "好的，已打开灯"
  turn_off_light: "好的，已关闭灯"
  fetching_news: "正在获取新闻，请稍候"